spring:
  datasource:
    url: jdbc:mysql://localhost:3306/caveat_emptor
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    spring.jpa.database-platform: org.hibernate.dialect.MySQL5Dialect
